base_url = "/"
title = "raaaandom"
description = "Welcome to my blog!"
theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
    highlight_code = true
    highlight_theme = "ayu-light"

[extra]
    theme = "toggle"
    menu = [
        { name = "/posts", url = "/posts", weight = 1 },
        { name = "/projects", url = "/projects", weight = 2 },
        { name = "/about", url = "/about", weight = 3 },
        { name = "/tags", url = "/tags", weight = 4 },
    ]
    socials = [
        { name = "github", url = "https://github.com/raaaandom/", icon = "github" },
    ]
    mathjax = true
    mathjax_dollar_inline_enable = true